server:
  port: 8090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 102466
  jackson:
    #设置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    #设置时区
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 100MB
      #      最大支持请求大小
      max-request-size: 100MB

#文件存储路径
#filepath: E:/file/
filepath: /usr/local/file
#通用数据源配置
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://10.110.2.56:3306/springboot_jpa?charset=utf8mb4&useSSL=false
# spring.datasource.username=springboot
#  spring.datasource.password=springboot
#  # Hikari 数据源专用配置
#  spring.datasource.hikari.maximum-pool-size=20
#  spring.datasource.hikari.minimum=5
  # JPA 相关配置
#  spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.ddl-auto=create
