spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 100MB
      #      最大支持请求大小
      max-request-size: 100MB
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    uaa:
      sensitiveHeaders:
    mss-business:
      sensitive-headers: Access-Control-Allow-Origin
      ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
security:
  oauth2:
    resource:
      user-info-uri:  http://uaa/user
      prefer-token-info: false
      loadBalanced: true
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
